service: my-serverless-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-2'}
  stage: ${opt:stage, 'prd'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${env:AWS_REGION, 'us-east-2'}:*:table/my-table

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  createItem:
    handler: handler.createItem
    events:
      - http:
          path: item
          method: post
